
name: 'dbt_impala_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_impala_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:         
  - "target"
  - "dbt_packages"


seeds:
  dbt_impala_demo:
    raw:
      covid: 
          +schema: raw_covid
    reference:
      +schema: reference

models:
  dbt_impala_demo:
    +materialized: view
    staging:
      covid:
        +schema: staging_covid
    marts:
      +materialized: table
      covid:
        +schema: mart_covid
